INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'Nike', 'https://www.nike.com/es/', 'http://localhost:8080/download/anuncio-nike.jpg');
INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'Adidas', 'https://www.adidas.es/', 'http://localhost:8080/download/anuncio-adidas.jpg');
INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'Joma', 'https://www.joma-sport.com/', 'http://localhost:8080/download/anuncio-joma.jpg');
INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'Puma', 'https://eu.puma.com/es/es/home', 'http://localhost:8080/download/anuncio-puma.jpg');
INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'Umbro', 'https://umbro.es/', 'http://localhost:8080/download/anuncio-umbro.jpg');
INSERT INTO ANUNCIOS (id, empresa, url, imagen) values (NEXTVAL('hibernate_sequence'), 'JD', 'https://www.jdsports.es/', 'http://localhost:8080/download/anuncio-jd.jpg');

INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Camisetas', 'http://localhost:8080/download/categoria-camisetas.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Shorts', 'http://localhost:8080/download/categoria-shorts.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Lifestyle', 'http://localhost:8080/download/categoria-lifestyle.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Bufandas', 'http://localhost:8080/download/categoria-bufandas.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Accesorios', 'http://localhost:8080/download/categoria-accesorios.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Botas', 'http://localhost:8080/download/categoria-botas.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Balones', 'http://localhost:8080/download/categoria-balones.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Banderas', 'http://localhost:8080/download/categoria-banderas.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Cromos', 'http://localhost:8080/download/categoria-cromos.jpg');
INSERT INTO CATEGORIAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Otra', 'http://localhost:8080/download/categoria-otra.png');

INSERT INTO SECCIONES (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Hombre', 'http://localhost:8080/download/seccion-hombre.jpg');
INSERT INTO SECCIONES (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Mujer', 'http://localhost:8080/download/seccion-mujer.jpg');
INSERT INTO SECCIONES (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Niño/a', 'http://localhost:8080/download/seccion-niñoa.png');
INSERT INTO SECCIONES (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Unisex', 'http://localhost:8080/download/seccion-unisex.jpeg');

INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Adidas', 'http://localhost:8080/download/marca-adidas.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Errea', 'http://localhost:8080/download/marca-errea.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Hummel', 'http://localhost:8080/download/marca-hummel.png');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Joma', 'http://localhost:8080/download/marca-joma.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Kappa', 'http://localhost:8080/download/marca-kappa.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Kelme', 'http://localhost:8080/download/marca-kelme.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Macron', 'http://localhost:8080/download/marca-macron.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'New Balance', 'http://localhost:8080/download/marca-nb.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Nike', 'http://localhost:8080/download/marca-nike.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Puma', 'http://localhost:8080/download/marca-puma.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Reebok', 'http://localhost:8080/download/marca-reebok.jpg');
INSERT INTO MARCAS (id, nombre, imagen) values (NEXTVAL('hibernate_sequence'), 'Umbro', 'http://localhost:8080/download/marca-umbro.png');

INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '<1 AÑO');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '1 AÑO');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '2 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '3 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '4 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '5 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '6 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '7 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '8 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '9 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '10 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '11 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '12 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '13 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '14 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '15 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '16 AÑOS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'XS');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'S');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'M');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'L');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'XL');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), 'XXL');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '3XL');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '20');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '21');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '22');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '23');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '24');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '25');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '26');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '27');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '28');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '29');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '30');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '31');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '32');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '33');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '34');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '35');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '36');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '37');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '38');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '39');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '40');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '41');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '42');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '43');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '44');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '45');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '46');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '47');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '48');
INSERT INTO TALLAS (id, nombre) values (NEXTVAL('hibernate_sequence'), '49');

INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Daniel', 'Oliva García', 'danieloliva', 'danieloliva@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'La Algaba', true, 'ADMIN');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Luis Miguel', 'López Magaña', 'luismilopez', 'luismilopez@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', true, 'ADMIN');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Miguel', 'Campos Rivera', 'miguelcampos', 'miguelcampos@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', true, 'ADMIN');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Antonio Jesús', 'Casanova Domínguez', 'jesuscasanova', 'jesuscasanova@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', true, 'ADMIN');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'José Javier', 'Bernal Morales', 'javierbernal', 'javierbernal@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', true, 'ADMIN');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Juan Carlos', 'Ardana Murillo', 'juancarlosardana', 'juancarlosardana@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Alejandro', 'Bajo Díaz', 'alejandrobajo', 'alejandrobajo@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Jesús', 'Barco Espinar', 'jesusbarco', 'jesusbarco@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Richard', 'Céspedes Pedrazas', 'richardcespedes', 'richardcespedes@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Sergio', 'Chamorro García', 'sergiochamorro', 'sergiochamorro@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Guillermo', 'De La Cruz Guzmán', 'guillermodelacruz', 'guillermodelacruz@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');
INSERT INTO USUARIOS (id, nombre, apellidos, username, email, password, avatar, localizacion, premium, rol) values (NEXTVAL('hibernate_sequence'), 'Daniel', 'De Luna Rodríguez', 'danieldeluna', 'danieldeluna@gmail.com', '12345678', 'http://localhost:8080/download/user.png', 'Triana', false, 'USER');


INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Real Betis 95/97', 'Esta camiseta es del Real Betis Balompie desde el año 1995 hasta el 1997. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-betis9597.jpg', 87, 17, 7, 25, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Arsenal 05/06', 'Esta camiseta es del Arsenal de la temporada 2005/2006. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-arsenal0506.jpg', 87, 17, 7, 29, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Atlético de Madrid 94/95', 'Esta camiseta es del Atlético de Madrid de la temporada 1994/1995. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-atm9495.jpg', 87, 17, 7, 30, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Barça 92/93', 'Esta camiseta es del FC Barcelona de la temporada 1992/1993. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-barça9293.jpg', 87, 17, 7, 25, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Bayern 86/87', 'Esta camiseta es del Bayern Munich de la temporada 1986/1987. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-bayern8687.jpg', 87, 17, 7, 21, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Fiorentina 92/93', 'Esta camiseta es de la Fiorentina de la temporada 1992/1993. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-fiorentina9293.jpg', 87, 17, 7, 32, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Inter 98/99', 'Esta camiseta es del Inter de Milán de la temporada 1998/1999. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-inter9899.jpg', 87, 17, 7, 29, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Madrid 98/99', 'Esta camiseta es del Real Madrid de la temporada 1998/1999. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-madrid9899.jpg', 87, 17, 7, 21, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta Milan 96/97', 'Esta camiseta es del AC Milan de la temporada 1996/1997. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-milan9697.jpg', 87, 17, 7, 32, 52);
INSERT INTO PRODUCTOS (id, titulo, descripcion, precio, intercambio, original, foto, usuario_id, seccion_id, categoria_id, marca_id, talla_id) values (NEXTVAL('hibernate_sequence'), 'Camiseta United 98/99', 'Esta camiseta es del Manchester United de la temporada 1998/1999. Es original y está en perfecto estado.', 50.00, false, true, 'http://localhost:8080/download/p-united9899.jpg', 87, 17, 7, 32, 52);